# Generated by Django 5.2.8 on 2025-11-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendamento",
            name="cliente",
        ),
        migrations.AddField(
            model_name="agendamento",
            name="nome_cliente",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="agendamento",
            name="telefone_cliente",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="agendamento",
            name="status",
            field=models.CharField(default="A", max_length=1),
        ),
    ]
